name: lando-lamp-laravel
recipe: lamp
config:
  webroot: app/public # lando needs to be able to resolve the dir to generate appserver urls, use a basic temp file (app/pubic/index.php) if app is not ready
proxy:
  appserver:
    - lando-lamp-laravel.lndo.site
services:
  appserver:
    config: {}
    ssl: true
    type: 'php:8.1'
    via: apache
    xdebug: false
    webroot: app/public
  database:
    config: {}
    authentication: mysql_native_password
    type: 'mysql:5.7'
    portforward: true
    creds:
      user: lamp
      password: lamp
      database: lamp
tooling:
  composer:
    service: appserver
    cmd: composer --ansi
  db-import <file>:
    service: ':host'
    description: Imports a dump file into a database service
    cmd: /helpers/sql-import.sh
    user: root
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      no-wipe:
        description: Do not destroy the existing database before an import
        boolean: true
  'db-export [file]':
    service: ':host'
    description: Exports database from a database service to a file
    cmd: /helpers/sql-export.sh
    user: root
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      stdout:
        description: Dump database to stdout
  php:
    service: appserver
    cmd: php
  mysql:
    service: ':host'
    description: Drops into a MySQL shell on a database service
    cmd: mysql -uroot
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
